### PR TITLE
Fix progressbar not resetting when done.

### LINKED ISSUE #10: [Visual] Download progress in task bar icon is off
Small visual issue with the progress in taskbar icon.
image
image

It seems to be one step off

### PR DESCRIPTION
**Pull request by DarkEyeDragon**
Fixes #10

### CODE REVIEW

File: src/launcher_downloader.js [hunk 1]
```diff
@@ -60,6 +60,10 @@ springDownloader.on('finished', (downloadItem) => {
 		wizard.isActive = false;
 		gui.send('dl-finished', downloadItem);
 		wizard.nextStep();
+		const mainWindow = gui.getMainWindow();
+		if (mainWindow != null) {
+			mainWindow.setProgressBar(-1);
+		}
```
Comment (p2004a) [inline src/launcher_downloader.js:66]: Could you also add the same on the `failed` handler?
